#!/usr/bin/env bash
require() {
  hash "$@" || exit
}
require cargo
usage() {
  echo "$0 <dir> [param1] [param2]..."
  exit 1
}
if test $# -ne 1 || test ! -d "$1"; then
  usage
fi
dir="$1"
shift
if test -e "${dir}/Cargo.toml"; then
  cargo run --manifest-path "${dir}/Cargo.toml" -- "$@"
else
  echo "The directory ${dir} must have a Cargo.toml file."
  exit 1
fi
